/* const productosCatalogo = [
    { id: 1 , nombre: 'APA', precio: 1500, categoria: 'cerveza', volumenAlcohol: 3.5},
    { id: 2 , nombre: 'IPA', precio: 1200, categoria: 'cerveza', volumenAlcohol: 4.5},
    { id: 3 , nombre: 'GOLDEN', precio: 1000, categoria: 'cerveza', volumenAlcohol: 2.0},
    { id: 4 , nombre: 'RED', precio: 1300, categoria: 'cerveza', volumenAlcohol: 2.7},
    { id: 5 , nombre: 'WINE', precio: 1350, categoria: 'cerveza', volumenAlcohol: 10},
    { id:10 , nombre: 'CLASICAS', precio: 2000, categoria: 'papas'},
    { id:11 , nombre: 'AMERICANAS', precio: 2500, categoria: 'papas'},
    { id:12 , nombre: 'CHEDDAR', precio: 3000, categoria: 'papas'},
    { id:13 , nombre: 'SALCHIPAPAS', precio: 4000, categoria: 'papas'},
    { id:20 , nombre: 'MOZZARELLA', precio: 4479, categoria: 'pizzas'},
    { id:21 , nombre: 'RUCULA', precio: 5000, categoria: 'pizzas'},
    { id:22, nombre: '4 QUESOS', precio: 4800, categoria: 'pizzas'},
    { id:23, nombre: 'NAPOLITANA', precio: 4799, categoria: 'pizzas'}, 
  ] */